In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import array

In [3]:
my_list = [1,2,3,4,5]
my_array_list = array.array('i',[1,2,3,4,5])
print(f"The data type of my_list is:{type(my_list)}")
print(f"The data type of my_array_list is:{type(my_array_list)}")

The data type of my_list is:<class 'list'>
The data type of my_array_list is:<class 'array.array'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import array

In [5]:
my_list = [1,2,3,4,5]
my_array_list = array.array('i',[1,2,3,4,5])

def print_element_types(collection,name):
    print(f"Data types of elements in {name}:")
    for i, element in enumerate(collection):
        print(f"Element {i}: {type(element)}")
    print()
print_element_types(my_list, 'my_list')
print_element_types(my_array_list,'my_array_list')

Data types of elements in my_list:
Element 0: <class 'int'>
Element 1: <class 'int'>
Element 2: <class 'int'>
Element 3: <class 'int'>
Element 4: <class 'int'>

Data types of elements in my_array_list:
Element 0: <class 'int'>
Element 1: <class 'int'>
Element 2: <class 'int'>
Element 3: <class 'int'>
Element 4: <class 'int'>



In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [ ]:
array_list = np.array(object = list_, dtype = int)

In [7]:
list_=[1.5,2.3,3.8]

In [ ]:
array_list = np.array(object = list_, dtype = int)

array([1,2,3])

In [ ]:
list_=['a','b','c']
array_list =np.array(object=list_,dtype=int)
ValueError:invalid literal for int() with base 10: 'a'

In [ ]:
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
import numpy as np

In [11]:
list_=[1,2.0,'3']

In [12]:
array_list= np.array(object=list_, dtype=int)

In [13]:
print("Data type in list_:")
for element in list_:
    print(type(element))
    
print("/nData types in array_list:")
for element in array_list:
    print(type(element))
    
num_list = [[1,2,3],[4,5.6]]
num_array = np.array(object= num_list)

print("/nData types in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))
        
print("/nData types in num_array:")
for element in np.nditer(num_array):
    print(type(element))
   
    

Data type in list_:
<class 'int'>
<class 'float'>
<class 'str'>
/nData types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
/nData types in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
/nData types in num_array:


/tmp/ipykernel_110/719262310.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  num_array = np.array(object= num_list)


TypeError: Iterator operand or requested dtype holds references, but the REFS_OK flag was not enabled

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [14]:
import numpy as np

In [15]:
num_array = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [17]:
shape=num_array.shape
size= num_array.size

In [18]:
print(f"Shape of the array:{shape}")

Shape of the array:(3, 3)


In [19]:
print(f"Size of the array:{size}")

Size of the array:9


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [20]:
import numpy as np

In [21]:
zero_matrix= np.zeros((3,3))
print("3*3 Matrix containing zeros:")
print(zero_matrix)

3*3 Matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [22]:
import numpy as np

In [23]:
identity_matrix =np.identity(5)
print("5*5 Identity Matrix:")
print(identity_matrix)


5*5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
import numpy as np

In [25]:
identity_matrix =np.eye(5)
print("5*5 Identity Matrix:")
print(identity_matrix)


5*5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
